spring:
  config:
    activate:
      on-profile: qa
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
  boot:
    admin:
      client:
        url: http://bootadmin.linker.ac

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  config: classpath:log/logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health

external:
  etoos:
    auth-url: https://stage-member.etoos.com
    auth-client-id: 03328164578a11672ae98e0d82e7847e
    auth-secret-key: faeb58a80ea8839105a39486079df9dfa15d054a1b2bbc8379711c1e0b227f9e
  sendbird:
    app-id: yNX/II7Sb11GzFewt9+Nlyv87z3Rif61+37jagT5yXSi/sclB0J4agKUjqSRU/Gw
    app-key: 74837d5d9ae732e87dfa1765a85f597dd729f4be16dc55d38e6613058698bd41

feign:
  linker:
    url: https://stage-linker.etoos.com