server:
  max-http-header-size: 24KB

spring:
  application:
    name: portal-main
  boot:
    admin:
      client:
        instance:
          name: ${spring.application.name}-${spring.config.activate.on-profile}
          prefer-ip: true